### ISSUE TITLE
Generate documentation 

### ISSUE THREAD

**Issue by wkramer** [Deltares/fews-pi-requests#27]
Create a Github workflow to generate documentation using `typedoc`.
https://typedoc.org

Use the `typedoc-github-wiki-theme`
https://github.com/tgreyuk/typedoc-plugin-markdown/tree/master/packages/typedoc-github-wiki-theme

Results should be made available as Github pages

**Comment by SaleemTheKing** [comment]
@wkramer This issue is a little conflicting with the provided information.

The package `github-wiki-theme` you provided is meant for pages on the GitHub wiki. This package creates `.md` files which is meant for the wiki.

GitHub pages requires `.html` files and is completely different from GitHub wiki.

Which one do you need?

**Comment by wkramer** [comment]
Do GitHub pages and html output.
